/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  rafae
 * Created: 05-nov-2019
 */
CREATE TABLE PROVINCIA
(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO CHAR(3) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_PROVINCIA_PK PRIMARY KEY (ID)
);

INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('ALV', 'ÁLAVA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('AB', 'ALBACETE');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('A', 'ALICANTE');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('AL', 'ALMERIA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('AS', 'ASTURIAS');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('AV', 'AVILA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('BA', 'BADAJOZ');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('IB', 'BALEARES');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('B', 'BARCELONA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('MA', 'MÁLAGA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('BU', 'BURGOS');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('CC', 'CÁCERES');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('CA', 'CÁDIZ');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('CAN', 'CANTABRIA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('C', 'CASTELLÓN');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('CR', 'CIUDAD REAL');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('CO', 'CORDOBA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('CU', 'CUENCA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('GR', 'GRANADA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('GI', 'GIRONA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('GU', 'GUADALAJARA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('G', 'GUIPUZCOA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('HU', 'HUELVA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('H', 'HUESCA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('J', 'JAÉN');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('R', 'LA RIOJA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('LP', 'LAS PALMAS');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('L', 'LEÓN');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('LL', 'LÉRIDA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('LU', 'LUGO');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('M', 'MADRID');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('MU', 'MURCIA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('N', 'NAVARRA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('PA', 'PALENCIA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('P', 'PONTEVEDRA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('SA', 'SALAMANCA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('SE', 'SEGOVIA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('S', 'SEVILLA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('SO', 'SORIA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('T', 'TARRAGONA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('TF', 'TENERIFE');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('TE', 'TERUEL');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('TO', 'TOLEDO');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('V', 'VALENCIA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('VA', 'VALLADOLID');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('VI', 'VIZCAYA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('ZA', 'ZAMORA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('Z', 'ZARAGOZA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('CE', 'CEUTA');
INSERT INTO PROVINCIA (CODIGO,NOMBRE) VALUES ('ML', 'MELILLA');

CREATE TABLE CLIENTE(
    DNI CHAR(9) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    DIRECCION VARCHAR(50),
    LOCALIDAD VARCHAR(30),
    PROVINCIA INTEGER,
    TELEFONO INTEGER,
    CONSTRAINT DNI_PK PRIMARY KEY (DNI),
    CONSTRAINT PROV_PERSONA_FK FOREIGN KEY (PROVINCIA) REFERENCES PROVINCIA (ID)
);

INSERT INTO CLIENTE VALUES ('25142741L','Pedro Montañez','C/Panamá Nº15','Alcobendas',1,987667666);
INSERT INTO CLIENTE VALUES ('12345678Q','Andrea Pirlo','C/Marina Nº16','Badalona',8,999999333);

CREATE TABLE RESERVAS_HAB(
    COD INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DNI_CLIENTE CHAR(9) NOT NULL REFERENCES CLIENTE(DNI),
    FECHA_ENTRADA DATE,  /*date	YYYY-MM-DD*/
    FECHA_SALIDA DATE,
    NUM_HABITACIONES INTEGER  NOT NULL,
    FUMADOR BOOLEAN DEFAULT FALSE,
    REGIMEN VARCHAR(25) CONSTRAINT REGIMEN_CK CHECK(REGIMEN IN('Alojamiento y desayuno', 'Media pension', 'Pension completa')),
    TIPO_HABITACION VARCHAR(25) CONSTRAINT TIPO_HABITACION_CK CHECK(TIPO_HABITACION IN('Sencilla', 'Doble uso individual', 'Suite Junior', 'Suite', 'Presidencial')),
    CONSTRAINT COD_RESERVAS_HAB PRIMARY KEY (COD)
);

CREATE TABLE RESERVAS_SALON(
    COD INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DNI_CLIENTE CHAR(9) NOT NULL REFERENCES CLIENTE(DNI),
    TIPO VARCHAR(20) NOT NULL CONSTRAINT TIPO_CK CHECK(TIPO IN('Banquete', 'Jornada', 'Congreso')),
    NUM_PERSONAS INTEGER NOT NULL,
    TIPO_COCINA VARCHAR(40) CONSTRAINT TIPO_COCINA_CK CHECK(TIPO_COCINA IN('No precisa', 'Bufet vegetariano', 'Bufet normal', 'Carta', 'Pedir cita con chef')),
    FECHA DATE NOT NULL,
    NUM_HABITACIONES INTEGER,
    NUM_DIAS INTEGER,
    CONSTRAINT COD_RESERVAS_SALON PRIMARY KEY (COD)
);

INSERT INTO RESERVAS_HAB(DNI_CLIENTE, FECHA_ENTRADA, FECHA_SALIDA, NUM_HABITACIONES, TIPO_HABITACION) VALUES ('12345678Q', '2019-11-15', '2019-11-15',10,'Doble uso individual');
INSERT INTO RESERVAS_SALON(DNI_CLIENTE, TIPO, NUM_PERSONAS, TIPO_COCINA, FECHA) VALUES ('25142741L','Banquete',25,'No precisa','2019-11-13');